### ISSUE TITLE
Publish on rubygems?

### ISSUE THREAD

**Issue by bufferoverflow** [netsphere-labs/omniauth-openid-connect#30]
I was search for this gem https://rubygems.org/search?utf8=%E2%9C%93&query=omniauth-openid-connect Do you plan to publish?

**Comment by hhorikawa** [comment]
This repository is a forked version.
Unfortunately, I can't submit it to rubygems.org.
Instead, I will provide a gem package when the upcoming version is available.

**Comment by bufferoverflow** [comment]
@hhorikawa Why do you not publish the gem under a new name?
