### ISSUE TITLE
Why not complete the fork and publish on Rubygems.org with new name?

### ISSUE THREAD

**Issue by pboling** [netsphere-labs/omniauth-openid-connect#38]
Why not complete the fork and publish on Rubygems.org with new name?

**Comment by hhorikawa** [comment]
@pboling 
Thank you for your suggestion.
OK, I'll try it.

**Comment by pboling** [comment]
@hhorikawa I don't see it yet!  https://rubygems.org/profiles/hhorikawa

Please ping a comment here when you have done it! :)

Here's the guide on how to publish to Rubygems.org:
https://guides.rubygems.org/publishing/#publishing-to-rubygemsorg

Of note - you will need to change the name of the gem to something different from the existing one.

**Comment by hhorikawa** [comment]
Thank you!
However, before uploading the gem file, I am going to ask m0n9oose-san if I can hand over the project.
Please check https://github.com/m0n9oose/omniauth_openid_connect/issues/101

**Comment by pboling** [comment]
Looks like the main gem is not part of the omniauth org, and we'll have to figure out how to merge these changes with the gitlab folks' changes.
